Add snapcraft metadata
zealdocs/packaging-snap pull request #1
Opened 2017-10-27 10:43 UTC by casept

This is more-or-less the same stuff as in my unofficial zeal snap repo. The manifest has been adapted to use cmake. It needs testing on other machines.

2017-10-27 11:07 UTC, trollixx commented
Thanks! I'll try to test this before merging and plugging to build.snapcraft.io.

Another question, is it possible to have daily builds pushed to edge, while only tagged releases would go to beta/stable?

2017-10-27 11:57 UTC, casept commented
> daily builds pushed to edge

AFAIK it's not possible to make `build.snapcraft.io` build on a schedule or when commits are made to a different repo than the one hosting the `snapcraft.yml` file. I think the "least hackish" option would be simply putting the snapcraft metadata into the main repo. That way a build and push to `edge` would be triggered by each new commit.

It would also make the `snapcraft.yml` easier to maintain. The `pull` step currently downloads a tagged release from GH, and building nightly builds would require a separate `snapcraft.yml` in a separate `packaging-snap-nightly` repo, whereas by letting the `snapcraft.yml` live in the main repo it could simply pull the source code from the directory it's in.

It would also ensure that if, for example, a user wishes to checkout an older version of zeal and build a snap package he would always have a working `snapcraft.yml` file for that particular point in history (because it's checked in alongside the source code). With the current model of storing the file separately the user would have to dig through this repo's history to hopefully find a version of the file that works with his particular commit in the main repo.

Another option might be to push an "empty" commit to this repo each time a nightly build should be pushed out, but that would require manual intervention or somewhat complex automation (and a server/CI service to run the automation on).

I'll ask on the snapcraft forum whether anyone knows a better workaround.

> tagged releases go to beta/stable

I'm not aware of any way to automate that using `build.snapcraft.io`, I think a 3rd party CI service with `snapcraft` support (or manually labelling a snap build as stable) would be needed to accomplish this.

2017-11-11 00:43 UTC, trollixx requested changes
Almost forgot about this, sorry. A few observations.

I wonder if IDE integration works with all isolation...

2017-11-11 00:43 UTC, trollixx commented on snapcraft.yaml
> +      - libqt5sql5-sqlite
Zeal doesn't use `libqt5sql5-sqlite` .

2017-11-11 00:43 UTC, trollixx commented on snapcraft.yaml
> +      - zlib1g-dev
Do all dependencies need to be listed explicitly? I am pretty sure some of these depend on others already.

2017-11-11 00:43 UTC, trollixx commented on snap/.snapcraft/state
> +!GlobalState
Isn't this file automatically generated?

2017-12-18 23:14 UTC, merged

2017-12-18 23:15 UTC, trollixx commented
Thanks! Sorry for the delay. Will try to hook this into snapcraft soon.